# SAM Configuration file for BV Squares deployment
version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bv-squares-stack"
s3_bucket = ""  # SAM will create this
s3_prefix = "bv-squares"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
confirm_changeset = true
fail_on_empty_changeset = false